In [1]:
#PROJECT & ORGANIZATION CHANGE MANAGEMENT TEST
#ABAHO BOAZ
#lets import libralies for our codes
import pandas as pd
import numpy as np

In [2]:
#loading data set
df=pd.read_csv("COVID_19 AMERICA 7.10.2021 1810PM.csv", sep=",")
df

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Transmission Classification
0,Bahamas,Americas,12407,3155.04,112,28.48,0,244,62.05,3,0.76,0,Clusters of cases
1,Turks and Caicos Islands,Americas,2424,6260.65,1,2.58,0,18,46.49,0,0.00,0,Clusters of cases
2,Antigua and Barbuda,Americas,1263,1289.71,0,0.00,0,42,42.89,0,0.00,0,Clusters of cases
3,Saint Barth√©lemy,Americas,1040,10520.99,8,80.93,0,1,10.12,0,0.00,0,Clusters of cases
4,British Virgin Islands,Americas,295,975.63,0,0.00,0,1,3.31,0,0.00,0,Clusters of cases
5,Dominica,Americas,192,266.70,1,1.39,0,0,0.00,0,0.00,0,Clusters of cases
6,United States of America,Americas,33257768,10047.58,82369,24.88,14239,597727,180.58,2136,0.65,355,Community transmission
7,Brazil,Americas,18169881,8548.14,541293,254.65,115228,507109,238.57,13416,6.31,2392,Community transmission
8,Argentina,Americas,4326101,9571.91,127481,282.06,27319,90986,201.32,3725,8.24,705,Community transmission
9,Colombia,Americas,4027016,7914.28,197137,387.43,29995,101947,200.36,4387,8.62,645,Community transmission
10,Mexico,Americas,2487747,1929.49,24357,18.89,4963,231847,179.82,1223,0.95,342,Community transmission
11,Peru,Americas,2036449,6176.33,21259,64.48,2843,191073,579.50,1551,4.70,167,Community transmission
12,Chile,Americas,1531872,8013.48,33641,175.98,3463,31797,166.34,657,3.44,51,Community transmission
13,Canada,Americas,1410927,3738.33,5781,15.32,721,26175,69.35,174,0.46,20,Community transmission
14,Ecuador,Americas,449483,2547.65,7142,40.48,376,21377,121.16,202,1.14,10,Community transmission
15,Bolivia (Plurinational State of),Americas,426748,3655.85,12235,104.81,2270,16329,139.89,503,4.31,86,Community transmission
16,Paraguay,Americas,411615,5770.95,12854,180.22,2148,11973,167.86,792,11.10,124,Community transmission
17,Panama,Americas,396526,9189.97,6305,146.13,1077,6491,150.44,34,0.79,8,Community transmission
18,Uruguay,Americas,360247,10370.61,13732,395.31,1786,5374,154.70,254,7.31,24,Community transmission
19,Costa Rica,Americas,357523,7018.35,10366,203.49,1903,4567,89.65,130,2.55,21,Community transmission
20,Dominican Republic,Americas,320136,2951.13,7321,67.49,882,3781,34.85,48,0.44,8,Community transmission
21,Guatemala,Americas,284741,1589.35,7814,43.62,2028,8845,49.37,296,1.65,60,Community transmission
22,Venezuela (Bolivarian Republic of),Americas,264551,930.34,9094,31.98,1179,3007,10.57,121,0.43,18,Community transmission
23,Honduras,Americas,255663,2581.25,5720,57.75,546,6844,69.10,153,1.54,26,Community transmission
24,Cuba,Americas,174789,1543.17,11374,100.42,1880,1209,10.67,85,0.75,16,Community transmission
25,Puerto Rico,Americas,139802,4886.72,308,10.77,21,2544,88.92,5,0.17,1,Community transmission
26,El Salvador,Americas,77484,1194.60,989,15.25,0,2351,36.25,36,0.56,5,Community transmission
27,Jamaica,Americas,49841,1683.15,338,11.41,46,1049,35.43,26,0.88,7,Community transmission
28,Trinidad and Tobago,Americas,31207,2229.89,1601,114.40,225,768,54.88,73,5.22,7,Community transmission
29,French Guiana,Americas,27040,9053.11,897,300.32,208,142,47.54,6,2.01,0,Community transmission
30,Suriname,Americas,20549,3502.88,1441,245.64,251,482,82.16,55,9.38,5,Community transmission
31,Guyana,Americas,19359,2461.25,701,89.12,125,454,57.72,16,2.03,2,Community transmission
32,Haiti,Americas,17963,157.54,915,8.02,27,400,3.51,31,0.27,0,Community transmission
33,Guadeloupe,Americas,17427,4355.40,139,34.74,0,266,66.48,1,0.25,0,Community transmission
34,Belize,Americas,13083,3290.26,89,22.38,24,329,82.74,2,0.50,0,Community transmission
35,Cura√ßao,Americas,12322,7509.16,18,10.97,1,125,76.18,2,1.22,0,Community transmission
36,Martinique,Americas,12199,3250.77,69,18.39,0,99,26.38,0,0.00,0,Community transmission
37,Aruba,Americas,11118,10413.43,29,27.16,2,107,100.22,0,0.00,0,Community transmission
38,Nicaragua,Americas,6402,96.64,159,2.40,0,190,2.87,1,0.02,0,Community transmission
39,Saint Lucia,Americas,5238,2852.52,50,27.23,11,84,45.74,4,2.18,0,Community transmission
40,Barbados,Americas,4052,1410.00,14,4.87,0,47,16.35,0,0.00,0,Community transmission
41,United States Virgin Islands,Americas,3819,3657.17,72,68.95,9,30,28.73,0,0.00,0,Community transmission
42,Sint Maarten,Americas,2585,6028.17,31,72.29,3,32,74.62,0,0.00,0,Community transmission
43,Saint Martin,Americas,2314,5985.67,86,222.46,0,26,67.25,1,2.59,0,Community transmission
44,Saint Vincent and the Grenadines,Americas,2207,1989.36,29,26.14,0,12,10.82,0,0.00,0,Community transmission
45,Bonaire,Americas,1608,7688.26,7,33.47,0,17,81.28,0,0.00,0,Community transmission
46,Saint Kitts and Nevis,Americas,396,744.47,145,272.60,19,3,5.64,3,5.64,0,Community transmission
47,Grenada,Americas,161,143.08,0,0.00,0,1,0.89,0,0.00,0,No cases
48,Anguilla,Americas,109,726.57,0,0.00,0,0,0.00,0,0.00,0,No cases
49,Montserrat,Americas,20,400.08,0,0.00,0,1,20.00,0,0.00,0,No cases
50,Sint Eustatius,Americas,20,637.15,0,0.00,0,0,0.00,0,0.00,0,No cases
51,Saba,Americas,7,362.13,0,0.00,0,0,0.00,0,0.00,0,No cases
52,Bermuda,Americas,2504,4021.00,5,8.03,0,33,52.99,0,0.00,0,Sporadic cases
53,Cayman Islands,Americas,609,926.66,10,15.22,0,2,3.04,0,0.00,0,Sporadic cases
54,Falkland Islands (Malvinas),Americas,60,1722.65,0,0.00,0,0,0.00,0,0.00,0,Sporadic cases
55,Saint Pierre and Miquelon,Americas,26,448.66,0,0.00,0,0,0.00,0,0.00,0,Sporadic cases

In [3]:
df.head()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Transmission Classification
0,Bahamas,Americas,12407,3155.04,112,28.48,0,244,62.05,3,0.76,0,Clusters of cases
1,Turks and Caicos Islands,Americas,2424,6260.65,1,2.58,0,18,46.49,0,0.00,0,Clusters of cases
2,Antigua and Barbuda,Americas,1263,1289.71,0,0.00,0,42,42.89,0,0.00,0,Clusters of cases
3,Saint Barth√©lemy,Americas,1040,10520.99,8,80.93,0,1,10.12,0,0.00,0,Clusters of cases
4,British Virgin Islands,Americas,295,975.63,0,0.00,0,1,3.31,0,0.00,0,Clusters of cases

In [4]:
df.tail()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Transmission Classification
51,Saba,Americas,7,362.13,0,0.00,0,0,0.00,0,0.0,0,No cases
52,Bermuda,Americas,2504,4021.00,5,8.03,0,33,52.99,0,0.0,0,Sporadic cases
53,Cayman Islands,Americas,609,926.66,10,15.22,0,2,3.04,0,0.0,0,Sporadic cases
54,Falkland Islands (Malvinas),Americas,60,1722.65,0,0.00,0,0,0.00,0,0.0,0,Sporadic cases
55,Saint Pierre and Miquelon,Americas,26,448.66,0,0.00,0,0,0.00,0,0.0,0,Sporadic cases

In [5]:
df.dtypes

Name                                                             object
WHO Region                                                       object
Cases - cumulative total                                          int64
Cases - cumulative total per 100000 population                  float64
Cases - newly reported in last 7 days                             int64
Cases - newly reported in last 7 days per 100000 population     float64
Cases - newly reported in last 24 hours                           int64
Deaths - cumulative total                                         int64
Deaths - cumulative total per 100000 population                 float64
Deaths - newly reported in last 7 days                            int64
Deaths - newly reported in last 7 days per 100000 population    float64
Deaths - newly reported in last 24 hours                          int64
Transmission Classification                                      object
dtype: object

In [6]:
df.describe()

,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours
count,5.600000e+01,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000,56.000000
mean,1.275874e+06,3935.451429,20456.053571,78.053571,3853.892857,33542.107143,74.064107,538.428571,1.768929,91.160714
std,5.038072e+06,3243.103255,78014.394954,103.899707,16162.765967,109808.602847,92.853474,1939.784410,2.770508,343.041041
min,7.000000e+00,96.640000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.057250e+03,1265.932500,9.500000,8.027500,0.000000,17.750000,10.645000,0.000000,0.000000,0.000000
50%,1.525500e+04,3053.085000,152.000000,27.855000,15.000000,255.000000,51.180000,3.500000,0.480000,0.000000
75%,3.294828e+05,6197.410000,7444.250000,101.517500,1102.500000,5653.250000,89.102500,135.750000,2.067500,18.500000
max,3.325777e+07,10520.990000,541293.000000,395.310000,115228.000000,597727.000000,579.500000,13416.000000,11.100000,2392.000000

In [7]:
df.shape

(56, 13)

In [8]:
%%capture
!pip install seaborn

In [9]:
df['Transmission Classification'].value_counts().to_frame()

                        Transmission Classification
Community transmission                           41
Clusters of cases                                 6
No cases                                          5
Sporadic cases                                    4

# Simple Linear Regression

In [10]:
#import matplotlib.pyplot as plt
#import numpy as np
#%conda install sklearn
#%matplotlib inline
#from sklearn.linear_model import linearRegression

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
#Using identified cases for the next 24 hours
x=df[['Cases - newly reported in last 24 hours']]
y=df['Deaths - newly reported in last 24 hours']

In [13]:
lm=LinearRegression()
lm.fit(x,y)
yhat=lm.predict(x)
yhat[0:5]

array([9.95968105, 9.95968105, 9.95968105, 9.95968105, 9.95968105])

In [14]:
#calculation of coefficient m
lm.coef_

array([0.02106987])

In [15]:
#intercept c
lm.intercept_

9.95968105413516

In [16]:
#calculating r-squared
lm.score(x,y)

0.9855145590117684

y=mx+c
$$Deaths - newly reported in last 24 hours=0.02106987xCases - newly reported in last 24 hours+9.95968105413516$$

In [17]:
#Let's import the function mean_squared_error from the module metrics
from sklearn.metrics import mean_squared_error

In [18]:
#RMSE
y=lm.predict(x)
MSE = mean_squared_error(df['Deaths - newly reported in last 24 hours'], y)
print('MSE is', MSE)

MSE is 1674.166108155738

In [19]:
#calculate RSME
#import necessary libraries
from math import sqrt

In [20]:
sqrt(mean_squared_error(df['Deaths - newly reported in last 24 hours'], y))

40.9165749807549

# Multiple LinearRegression

Predicting Deaths-newly reported in last 24 hours in America by looking at; Cases - newly reported in last 7 days,cases - cumulative total per 100000 population, and Cases - newly reported in last 24 hours


Model formulae;
$$ùë¶=ùëè1ùë•1+ùëè2ùë•2+b3x3+ùëê$$

In [21]:
# The different variables here are; Cases - newly reported in last 7 days, cases - cumulative total per 100000 population and Cases,Cases - newly reported in last 24 hours
z = df[['Cases - newly reported in last 7 days', 'Cases - cumulative total per 100000 population','Cases - newly reported in last 24 hours']]

In [22]:
#Fitting the linear model using the three above-mentioned variables.
lm.fit(z, df['Deaths - newly reported in last 24 hours'])

LinearRegression()

In [23]:
#calculation of coefficient b1,b2,b3 
lm.coef_

array([0.0002005 , 0.00085955, 0.02005241])

In [24]:
#intercept 
lm.intercept_

6.396806461731813

In [25]:
#calculating r-squared
lm.score(z, df['Deaths - newly reported in last 24 hours'])

0.9856121774537552

In [26]:
#Calculating the Mean Squared Error (MSE)
#prediction based on our model
y_predict_multifit = lm.predict(z)
#Now we can compare the predicted results with the actual results
mean_squared_error(df['Deaths - newly reported in last 24 hours'], y_predict_multifit)

1662.883780801116

In [27]:
#calculating RMSE
sqrt(mean_squared_error(df['Deaths - newly reported in last 24 hours'], y_predict_multifit))

40.778472026316976

# The best design model to predict the number of deaths due to Covid_19 pandemic in Americas Region is Multiple Linear Regression.

# Reason

# r-square for Multiple Linear Regression = 0.9856121774537552 which is Higher than the r-square for Simple LinearRegression = 0.9855145590117684